name: docker & singularity/cvmfs releases

on:
  push:
    # on push tags only
    branches-ignore:
      - '**'
    tags:
      - '**'
  workflow_dispatch:
    inputs:
      tag:
        description: 'the tag to publish and possibly overwrite'
        default: 'dev'
        required: false
  delete:
    branches:
      - '**'

jobs:
  image-publish:
    uses: WIPACrepo/wipac-dev-workflows/.github/workflows/image-publish.yml@v1.11
    permissions: # for GITHUB_TOKEN
      packages: write
    with:
      image_registry: ghcr.io
      image_namespace: observation-management-service
      image_name: ewms-task-management-service
      mode: ${{ github.event_name == 'delete' && 'CVMFS_REMOVE' || 'CVMFS_BUILD' }}
      cvmfs_dest_dir: ewms
      # cvmfs-remove options...
      cvmfs_remove_tags: '${{ github.ref_name }}-[SHA]'
      # build options...
      extra_build_tag: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.tag || '' }}
    secrets:
      cvmfs_github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
