name: docker & singularity/cvmfs releases


on:
  push:
    branches-ignore:
      - '**'
    tags:
      - '**'
  workflow_dispatch:
  delete:


env:
  DOCKER_IMAGE_NAME: ghcr.io/observation-management-service/ewms-task-management-service
  CVMFS_DEST_SUBDIR: ewms


jobs:

  docker:
    name: "Docker Image"
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Project
      uses: actions/checkout@v3
    - name: Docker meta
      id: docker_meta
      uses: docker/metadata-action@v3
      with:
        images: |
          ${{ env.DOCKER_IMAGE_NAME }}
        tags: |
            type=ref,event=branch
            type=semver,pattern={{major}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}.{{minor}}.{{patch}}
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Push Docker Image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ steps.docker_meta.outputs.tags }}
        labels: ${{ steps.docker_meta.outputs.labels }}

  cvmfs:
    name: CVMFS Image
    needs: [docker]
    runs-on: ubuntu-latest
    steps:

    - name: Checkout Project
      uses: actions/checkout@v3

    - name: Docker meta
      id: docker_meta
      uses: docker/metadata-action@v4
      with:
        images: |
          ${{ env.DOCKER_IMAGE_NAME }}
        flavor: |
          latest=false
        tags: |
          # we only want to put version/sha -specific images on CVMFS
          # branches (PRs)
          type=sha,prefix={{branch}}-,enable=${{ github.ref_type == 'branch' }}
          # release tags
          type=semver,pattern={{major}}.{{minor}}.{{patch}},enable=${{ github.ref_type == 'tag' }}

    - name: Request Build(s)
      if: github.event_name != 'delete'
      uses: WIPACrepo/build-singularity-cvmfs-action@v1.2
      with:
        github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}  # so job can git push
        docker_tags: ${{ steps.docker_meta.outputs.tags }}
        dest_dir: ${{ env.CVMFS_DEST_SUBDIR }}
        include_docker_repo: false
